[target.'cfg(target_arch = "x86_64")']
rustflags = ["-C", "target-cpu=x86-64-v2", "-C", "target-feature=+avx"]

[target.'cfg(not(target_os = "linux"))']
rustflags = ["-C", "target-feature=+crt-static"]
