name: Build

on: [push, pull_request]

jobs:
  build-windows:
    name: Build windows
    runs-on: windows-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Build
        run: |
          rustup override set nightly
          cargo build --release

      - uses: actions/upload-artifact@v6
        with:
          name: ReAET-windows
          path: target/release/ReAET.exe

  build-macos:
    name: Build macos
    runs-on: macos-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Build
        run: |
          rustup override set nightly
          cargo build --release

      - uses: actions/upload-artifact@v6
        with:
          name: ReAET-macos-aarch64
          path: target/release/ReAET

  build-linux:
    name: Build linux
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Build
        run: |
          sudo apt-get update
          sudo apt-get install libglib2.0-dev
          rustup override set nightly
          cargo build --release

      - uses: actions/upload-artifact@v6
        with:
          name: ReAET-linux
          path: target/release/ReAET
